Areas/admin/Controllers/BillController.cs
using BTL_NET2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_NET2.Areas.admin.Controllers
{
    public class BillController : Controller
    {
        // GET: admin/Bill
        Model1 data = new Model1();
        public ActionResult Index()
        {
            var hoadon = (from i in data.bills select i).ToList();
            ViewBag.hoadon = hoadon;
            return View();
        }

        public ActionResult DS_Bill(int idBill)
        {            
            var bil = (from cm in data.billdetails where cm.billID == idBill select cm).ToList();
            var nameBill = from i in data.bills where i.id == idBill select i;

            ViewBag.bil = bil;
            ViewBag.nameBill = nameBill;

            return View();
        }

        public ActionResult Xoa_bill(int idBill)
        {
            bill bi = data.bills.SingleOrDefault(n => n.id == idBill);
            //billdetail bill = data.billdetails.SingleOrDefault(n => n.billID == idBill);
            if (bi == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.bills.Remove(bi);
            //data.billdetails.Remove(bill);
            data.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Xoa_billdetail(int idBilldetail)
        {
            billdetail bi = data.billdetails.SingleOrDefault(n => n.id == idBilldetail);
            if (bi == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.billdetails.Remove(bi);
            data.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Areas/admin/Controllers/CategoryController.cs
using BTL_NET2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_NET2.Areas.admin.Controllers
{
    public class CategoryController : Controller
    {
        // GET: admin/Category
        Model1 data = new Model1();
        public ActionResult Index()
        {
            var theloai = data.categories.ToList();
            var loai = (from i in data.categories select i).ToList();
            ViewBag.loai = loai;
            return View();
        }

        public ActionResult DS_theloai(int idTheLoai)
        {
            var tl = (from cm in data.PRODUCTs where cm.catID == idTheLoai orderby cm.id descending select cm).ToList();
            var nameTL = from i in data.categories where i.id == idTheLoai select i;

            ViewBag.tl = tl;
            ViewBag.name = nameTL;
            return View();
        }

        [HttpGet]
        public ActionResult Them_TheLoai()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Them_TheLoai(category theloai)
        {
            category ca = new category();
            ca.created_at = DateTime.Now;
            ca.update_at = DateTime.Now;
            data.categories.Add(ca);
            data.categories.Add(theloai);
            data.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sua_sanpham(int id)
        {
            var sua = data.PRODUCTs.First(n => n.id == id);
            return View(sua);
        }

        [HttpPost]
        public ActionResult Sua_sanpham(int id, FormCollection collection)
        {
            var sua = data.PRODUCTs.First(n => n.id == id);
            string sTen = collection["name"];
            string sNguoinhap = collection["author"];
            int sGia = int.Parse(collection["price"]);
            byte sGiamgia = Byte.Parse(collection["discount"]);
            string sHang = collection["producer.name"];
            string sLoai = collection["category.name"];
            string sMota = collection["description"];
            byte sStatus = Byte.Parse(collection["status"]);

            sua.id = id;
            sua.name = sTen;
            sua.author = sNguoinhap;
            sua.price = sGia;
            sua.discount = sGiamgia;
            sua.producer.name = sHang;
            sua.category.name = sLoai;
            sua.description = sMota;
            sua.status = sStatus;
            sua.created_at = DateTime.Now;

            UpdateModel(sua);
            data.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Xoa_theloai(int idTheLoai)
        {
            category cate = data.categories.SingleOrDefault(n => n.id == idTheLoai);
            if(cate == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.categories.Remove(cate);
            data.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Xoa_sanpham(int idSP)
        {
            PRODUCT pro = data.PRODUCTs.SingleOrDefault(n => n.id == idSP);
            if (pro == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.PRODUCTs.Remove(pro);
            data.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/admin/Controllers/HomeController.cs
using BTL_NET2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_NET2.Areas.admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: admin/Default
        Model1 data = new Model1();
        public ActionResult Index()
        {
            var loai = (from i in data.categories select i).ToList();
            var loai1 = (from ca in data.categories
                         join pr in data.PRODUCTs on ca.id equals pr.catID
                         where ca.id == 1 select ca ).ToList();
            
            var prod = (from i in data.PRODUCTs select i).ToList();
            var bill = (from i in data.bills select i).ToList();
            var user = (from i in data.accounts select i).ToList();

            //comment
            var cmt = (from i in data.feedbacks orderby i.id descending select i).Take(10).ToList();
            //foreach(var im in cmt)
            //{
            //    ViewBag.id = im.id;
            //    //var cmt1 = (from i in data.feedbacks where i.accountid == im.id select i).Take(10).ToList();
               
            //}


            //hiển thị danh tổng số cmt theo user
            var SumCmt = (from i in data.accounts select i).ToList();

            ViewBag.loai = loai;
            ViewBag.dem = loai.Count();
            ViewBag.loai_1 = loai1.Count();
            ViewBag.demprod = prod.Count();
            ViewBag.dembill = bill.Count();
            ViewBag.demuser = user.Count();
            ViewBag.cmt = cmt;
           
            ViewBag.SumCmt = SumCmt;

            return View();
        }
    }
}

Areas/admin/Controllers/ProductsController.cs
using BTL_NET2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_NET2.Areas.admin.Controllers
{
    public class ProductsController : Controller
    {
        // GET: admin/Products
        Model1 data = new Model1();
        public ActionResult Index()
        {
            var sp = (from i in data.PRODUCTs select i).ToList();
            ViewBag.sp = sp;
            var sp1 = data.PRODUCTs.ToList();
            return View();
        }

        [HttpGet]
        public ActionResult Them_sampham()
        {
            return View();
        }        

        [HttpPost]
        public ActionResult Them_sanpham(PRODUCT pro)
        {
            data.PRODUCTs.Add(pro);
            data.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sua_sanpham(int id)
        {
            var sua = data.PRODUCTs.First(n => n.id == id);
            return View(sua);
        }

        [HttpPost]
        public ActionResult Sua_sanpham(int id, FormCollection collection)
        {
            var sua = data.PRODUCTs.First(n => n.id == id);
            string sTen = collection["name"];
            string sNguoinhap = collection["author"];
            int sGia = int.Parse(collection["price"]);
            byte sGiamgia = Byte.Parse(collection["discount"]);
            string sHang = collection["producer.name"];
            string sLoai = collection["category.name"];
            string sMota = collection["description"];
            byte sStatus = Byte.Parse(collection["status"]);

            sua.id = id;
            sua.name = sTen;
            sua.author = sNguoinhap;
            sua.price = sGia;
            sua.discount = sGiamgia;
            sua.producer.name = sHang;
            sua.category.name = sLoai;
            sua.description = sMota;
            sua.status = sStatus;
            sua.created_at = DateTime.Now;

            UpdateModel(sua);
            data.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Xoa_sanpham(int idSP)
        {
            PRODUCT pro = data.PRODUCTs.SingleOrDefault(n => n.id == idSP);
            //feedback fe = data.feedbacks.FirstOrDefault(n => n.productid == idSP);
            if (pro == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.PRODUCTs.Remove(pro);
            //data.feedbacks.Remove(fe);
            data.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Areas/admin/Controllers/UserController.cs
using BTL_NET2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BTL_NET2.Areas.admin.Controllers
{
    public class UserController : Controller
    {
        // GET: admin/User
        Model1 data = new Model1();
        private object dangnhap;

        public ActionResult Index()
        {
            var user = (from i in data.accounts select i).ToList();
           ViewBag.user = user;
            return View();
        }

        //comment từ trang chủ chuyển sang----------
        public ActionResult Comment(int id)
        {
            //hiển thị cmt theo id account
            var cmt = (from cm in data.feedbacks where cm.accountid == id orderby cm.id descending select cm).ToList();
            ViewBag.cmt = cmt;
            return View();
        }

        public ActionResult XoaCmt(int idcmt)
        {
            feedback fe = data.feedbacks.SingleOrDefault(n => n.id == idcmt);
            if(fe == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            data.feedbacks.Remove(fe);
            data.SaveChanges();
            
            return RedirectToAction("Hien_cmt");
        }
        //----------------------------------------------

        public ActionResult Hien_cmt()
        {
            var SumCmt = (from i in data.accounts select i).ToList();
            ViewBag.SumCmt = SumCmt;
            return View();
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(FormCollection collection)
        {
            string TK = collection.Get("txtEmail").ToString();
            string MK = collection.Get("txtMatKhau").ToString();
            account dangnhap = data.accounts.SingleOrDefault(n => n.email == TK && n.password == MK && n.role==1);
            if (dangnhap != null)
            {

                Session["TaiKhoan"] = dangnhap;                
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Sai Email hoặc mật khẩu. Vui lòng thử lại!");
                return Redirect("Login");
            }
        }

        //thông tin đăng nhập
        public ActionResult Info()
        {
            return View();
        }

        //thông tin các tài khoản
        public ActionResult User_info(int id)
        {
            account us = data.accounts.SingleOrDefault(n => n.id == id);
            var tk = (from i in data.accounts where i.id == id select i).ToList();
            ViewBag.tk = tk;
            return View(us);
        }
    }
}

Areas/admin/Views/Home/Index.cshtml
@using BTL_NET2.Models;
@using PagedList;
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/admin/Views/Shared/_Layout.cshtml";
}

@*@foreach (var i in @ViewBag.product)
    {
        @i.name
    }*@

<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <a href="#">Dashboard</a>
    </li>
    <li class="breadcrumb-item active">Overview</li>
</ol>

<!-- Icon Cards-->
<div class="row">
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-primary o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-comments"></i>
                </div>
                <div class="mr-5">Thể loại: @ViewBag.dem</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index","Category")">
                <span class="float-left">Xem chi tiết</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-warning o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-list"></i>
                </div>
                <div class="mr-5">Sản phẩm: @ViewBag.demprod</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index","Products")">
                <span class="float-left">Xem chi tiết</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-success o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-shopping-cart"></i>
                </div>
                <div class="mr-5">Hóa đơn: @ViewBag.dembill</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index","Bill")">
                <span class="float-left">Xem chi tiết</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
    <div class="col-xl-3 col-sm-6 mb-3">
        <div class="card text-white bg-danger o-hidden h-100">
            <div class="card-body">
                <div class="card-body-icon">
                    <i class="fas fa-fw fa-life-ring"></i>
                </div>
                <div class="mr-5">Tài khoản: @ViewBag.demuser</div>
            </div>
            <a class="card-footer text-white clearfix small z-1" href="@Url.Action("Index","User")">
                <span class="float-left">Xem chi tiết</span>
                <span class="float-right">
                    <i class="fas fa-angle-right"></i>
                </span>
            </a>
        </div>
    </div>
</div>

<!-- Area Chart Example-->
@*<div class="card mb-3">
        <div class="card-header">
            <i class="fas fa-chart-area"></i>
            Area Chart Example
        </div>
        <div class="card-body">
            <canvas id="myAreaChart" width="100%" height="30"></canvas>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
    </div>*@

<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Thể loại
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Loại</th>
                        <th>Số lượng</th>
                        <th>Ngày nhập</th>
                        <th>Cập nhật cuối</th>
                        <th>Chi tiết</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>STT</th>
                        <th>Loại</th>
                        <th>Số lượng</th>
                        <th>Ngày nhập</th>
                        <th>Cập nhật cuối</th>
                        <th>Chi tiết</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var i in ViewBag.loai)
                    {
                        
                        <tr>
                            <td>@i.id</td>
                            <td>@i.name</td>
                            <td>@i.PRODUCTs.Count</td>
                            @*<td>
                                @{
                                    if (i.status == 1)
                                    {
                                        <span>Còn</span>
                                    }
                                    else
                                    {
                                        <span>Hết</span>
                                    }
                                }
                            </td>*@
                            <td>@i.created_at</td>
                            <td>@i.update_at</td>
                            <td><a href="@Url.Action("DS_theloai", "Category", new {@idTheLoai=i.id})" class="btn btn-primary">Danh sách</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>
</div>



<!-- DataTables Example -->
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Phản hồi nhiều nhất
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>STT</th>
                        <th>Tên</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th>Tổng số bình luận</th>
                        <th>Chi tiết</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>STT</th>
                        <th>Tên</th>
                        <th>Địa chỉ</th>
                        <th>Số điện thoại</th>
                        <th>Email</th>
                        <th>Tổng số bình luận</th>
                        <th>Chi tiết</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var i in @ViewBag.SumCmt)
                    {
                        <tr>
                            <td>@i.id</td>
                            <td>@i.name</td>
                            <td>@i.address</td>
                            <td>@i.phone</td>
                            <td>@i.email</td>   
                            <td>@i.feedbacks.Count</td>
                            <td><a href="@Url.Action("Comment", "User", new {name= i.name, id = i.id})" class="btn btn-primary" title="Xem"><i class="fas fa-eye"></i>&nbsp;&nbsp; Xem</a></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



<!-- DataTables Example -->
@*<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        Phản hồi gần đây nhất
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Sản phẩm</th>
                        <th>Người dùng</th>
                        <th>Bình luận</th>
                        <th>Thời gian</th>
                        <th>Chi tiết</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>Sản phẩm</th>
                        <th>Người dùng</th>
                        <th>Bình luận</th>
                        <th>Thời gian</th>
                        <th>Chi tiết</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var i in ViewBag.cmt)
                    {
                        var url = "/chi-tiet-comment/" + i.account.email + "-" + i.PRODUCT.name;
                        <tr>
                            <td>@i.PRODUCT.name</td>
                            <td>@i.account.email</td>
                            <td>@i.comment</td>
                            <th>@i.created_at</th>
                            <th><a href="@url" class="btn btn-primary">Xem</a></th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>*@